### PR TITLE
Openapi generate

### PR DESCRIPTION
**Pull request by bechurch**
# Overview
This overhauls our typescript-client to:
1. be generated by OpenApi-generate
2. generate our docs as markdown
3. have our updated github project template

## Notes for reviewers:
1. I'm not a big fan of what the generated API turns out to be like. Tinker with it and let me know your thoughts
2. We still very much have to keep the main readme up to date

### CODE REVIEW

**Comment by dholms** [comment]
Yeah not crazy about the docs here at all so we'll need to maintain those ourselves.

The package also loses some readability I think, just in terms of code (ie things like `userPost` instead of `register`). I imagine most people using a client library will use javascript, and the package is small enough that the overhead to maintain it is pretty low. I'm curious what you think about leaving this package hand rolled and using Openapi to generate client libraries for other languages?

**Comment by bmann** [comment]
> I'm curious what you think about leaving this package hand rolled and using Openapi to generate client libraries for other languages?

Yes to this. Over time, ideally we end up with third-party maintainers for these things and/or see which of them we maintain as a first party.

**Comment by bechurch** [comment]
@dholms I think thats really fair criticism. I would be fine turning to writing these by hand. Honestly putting this up was most likely me falling victim to sunk cost. 😬

**Comment by expede** [comment]
I've said this elsewhere, but to get it into the contextual thread:

Okay, all of this makes sense. Let's take what we've learned in this process to support other ecosystems, but TS is so critical that we hand-roll it.

Also: in either case, we need to add updating clients to our `web-api` development workflow

**Comment by bechurch** [comment]
Closing in favour of https://github.com/fission-suite/typescript-client/pull/22

**Pull request closed without merging**
